name: pokedex
description: Pokedex Franq
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  asuka: ^2.0.1+3
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.0.0-alpha.2
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5
  result_dart: ^1.0.5
  firebase_core: ^2.5.0
  firebase_analytics: ^10.1.1
  firebase_crashlytics: ^3.0.12
  firebase_auth: ^4.2.6
  responsive_framework: ^0.2.0
  dio: ^4.0.6
  flutter_svg: ^2.0.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  # modular_test: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/pokeball.png
   - assets/images/pokeball_dark.png

